name: Telegram Reminder Bot

on:
  workflow_dispatch: # Allow manual triggering
  push:              # Trigger on push to main
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: production
    permissions:
        contents: read
     
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Debug environment variables
      - name: Debug environment
        run: |
          echo "Testing if TOKEN is set..."
          echo "TOKEN=$TOKEN"
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the bot
      - name: Run bot
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python bot.py
